# Generated by Django 2.2.2 on 2021-06-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('web', 'web developer'), ('ui', 'ui/ux developer'), ('android', 'andriod developer')], default='', max_length=100),
        ),
    ]
