# Generated by Django 2.2.2 on 2021-06-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20210602_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, default='developer', max_length=100, null=True),
        ),
    ]
