# Generated by Django 2.2.2 on 2021-06-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20210609_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='images/images.profile.png', null=True, upload_to='images'),
        ),
    ]
