# Generated by Django 2.2.2 on 2021-05-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_leader',
        ),
    ]
