# Generated by Django 2.2.2 on 2021-05-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectlead', '0002_auto_20210509_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
