# Generated by Django 2.2.2 on 2021-05-25 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectlead', '0005_tasks_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='employee',
        ),
        migrations.CreateModel(
            name='TaskAssigned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectlead.Tasks')),
            ],
        ),
    ]
