# Generated by Django 2.2.2 on 2021-06-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectlead', '0006_auto_20210525_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='task_complete',
        ),
        migrations.AddField(
            model_name='taskassigned',
            name='task_status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
