# Generated by Django 2.2.2 on 2021-06-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectlead', '0007_auto_20210602_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassigned',
            name='task_priority',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
