# Generated by Django 2.2.2 on 2021-06-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectlead', '0010_tasks_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
