# Generated by Django 2.2.2 on 2021-06-05 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_remove_project_project_leader'),
        ('projectlead', '0011_tasks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassigned',
            name='project',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='hr.Project'),
        ),
    ]
