# Generated by Django 2.2.2 on 2021-06-05 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectlead', '0012_taskassigned_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassigned',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Project'),
        ),
    ]
